[package]
name = "hbar-desktop"
version = "0.1.0"
description = "hbar desktop workbench"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dunce = "1.0.5"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
